extends Node

const PERSONALITY_AMABLE: String = "amable"
const PERSONALITY_GRUNON: String = "grunon"
const PERSONALITY_IMPREDECIBLE: String = "impredecible"

const MOOD_HAPPY: String = "happy"
const MOOD_NEUTRAL: String = "neutral"
const MOOD_IRRITATED: String = "irritated"

const DIALOGUE_FIRST_HAPPY: String = "first_happy"
const DIALOGUE_FIRST_IRRITATED: String = "first_irritated"
const DIALOGUE_SECOND_POSITIVE: String = "second_positive"
const DIALOGUE_SECOND_NEGATIVE: String = "second_negative"
const DIALOGUE_SECOND_NEUTRAL: String = "second_neutral"
const DIALOGUE_LIMIT_HAPPY: String = "limit_happy"
const DIALOGUE_LIMIT_IRRITATED: String = "limit_irritated"
const DIALOGUE_LIMIT_NEUTRAL: String = "limit_neutral"
const DIALOGUE_GIFT_LOVED: String = "gift_loved"
const DIALOGUE_GIFT_LIKED: String = "gift_liked"
const DIALOGUE_GIFT_NEUTRAL: String = "gift_neutral"
const DIALOGUE_GIFT_DISLIKED: String = "gift_disliked"
const DIALOGUE_GIFT_ALREADY_RECEIVED: String = "gift_already_received"

const GIFT_COMIDA: String = "comida"
const GIFT_FLOR: String = "flor"
const GIFT_JOYA: String = "joya"
const GIFT_LIBRO: String = "libro"
const GIFT_ARTESANIA: String = "artesania"
const GIFT_EXTRANO: String = "extrano"
